### ISSUE TITLE
next() in Stepper does not exist on type 'Vue'

### ISSUE THREAD

**Issue by irhamputra** [quasarframework/app-extension-typescript#49]
Hi 👋🏼

Currently I'm facing a problem with Stepper in TypeScript. Since the ``this.$refs.stepper.next()``does not exist in type Vue. so I can't programmatically navigate the stepper to next panel. Maybe I was missing something to import 😢 because the docs doesn't explain enough with TS

FYI: Currently I'm using Vue CLI

How should I solve this problem?

**Comment by irhamputra** [comment]
Got the answer after workaround

```ts
onNext() {
   (this.$refs.stepper as QStepper).next()
}
```

**Comment by IlCallo** [comment]
Exactly, `this.$refs` isn't typed to the actual component instance (and probably never will) so you have to cast it

**Comment by doic** [comment]
How would you do that with Composition API (no access to 'this') ??

**Comment by hawkeye64** [comment]
@doic I would assume you use the `ref="myRef"` you used in the template that matches your `const myRef = ref(null)` variable.

**Comment by doic** [comment]
Tried that, but couldn't infer the type properly. JS works fine though.
The solution I found is
```vue
<template>
    <q-btn @click="previous($refs.stepper)" label="Back" />
</template>
```
```typescript
function previous(r:any) {
    (r as QStepper).previous()
}
```

**Comment by IlCallo** [comment]
> this.$refs isn't typed to the actual component instance (and probably never will) so you have to cast it

`const stepper = ref<QStepper>()` is your way to go

**Comment by doic** [comment]
I tried that earlier, the problem was I couldn't access `previous()` method on a `Ref<QStepper>`:
```typescript
const stepper = ref<QStepper>()
function previous(){
  stepper.previous()
}
```
`Property 'previous' does not exist on type 'Ref<QStepper | undefined>'`
Maybe I did it wrong ?

**Comment by IlCallo** [comment]
@doic you have to check if the ref is actually filled or not...
Or cast it to not have `undefined`, if you are sure you'll be using it after the component has been mounted: `const stepper = ref() as Ref<QStepper>`

**Comment by doic** [comment]
Just tried `const stepper = ref() as Ref<QStepper>` and got `Property 'previous' does not exist on type 'Ref<QStepper>'`

Apparently the problem is `Ref<QStepper>` != `QStepper`

**Comment by IlCallo** [comment]
I think you probably need to get back to the basic a bit 😅 
Please check out how do [Composition API](https://v3.vuejs.org/guide/composition-api-introduction.html) works, especially related to refs.

The short answer is: of course `Ref<QStepper>` != `QStepper`, you should access it as `stepper.value.previous()` since it's a `ref`

**Comment by doic** [comment]
Now that makes sense 😅
I used `stepper.previous()` in all my previous messages though 😅
Thanks for the help, now it works fine, without any complex workaround !

**Comment by doic** [comment]
No, not working. IDE was ok apparently, but I get this error in Chrome:
`Uncaught (in promise) TypeError: Cannot read property 'promise' of undefined`
So I'll get back to my workaround. I'm sorry that using the code in Quasar Documentation doesn't make it 😅

**Comment by IlCallo** [comment]
> I used stepper.previous() in all my previous messages though sweat_smile
In your first message that usage was in fact correct because `$refs.stepper` is of type `QStepper`
I didn't saw the error in your second example as I was focusing on the definition instead. 

Quasar v1 docs show how you can do it via Options API, because when it was written Compositon API simply didn't exist.
All examples there, and on the new Quasar v2 docs, works, they simply don't cover all cases. In this case, because "calling a method on a component" is supposed to be such an easy thing to do that we literally cannot add an example for every method which can be called of every component.
That's why I suggested you to go back and re-read the basics of Composition API

Anyway, please use Discord or GitHub Discussions to ask for assistance from the community, there's people which could help you get in the gears and provide examples faster than on issues, which are meant to report errors

**Comment by danieleades** [comment]
hey @doic, did you figure this out?

i'm scratching my head

**Comment by doic** [comment]
No @danieleades, I stopped after my workaround, and haven't tried later. Maybe now Quasar v2 docs show how it works with Vue 3 Composition API ?

**Comment by danieleades** [comment]
> No @danieleades, I stopped after my workaround, and haven't tried later. Maybe now Quasar v2 docs show how it works with Vue 3 Composition API ?

Actually I just figured it out. In my case, It turned out the ref to the QStepper was fine, but the value tied to the step number was a bare integer. Once I wrapped that in a ref too everything started working
